# -*- mode: sh; -*-
# vim: set ft=sh sw=2 sts=2:

[ ! -f "$HOME/.path" ] || source "$HOME/.path"

if command -v mise >/dev/null ; then
  eval "$(mise activate bash --shims)"
fi

[ ! -f "$HOME/.bashrc" ] || source "$HOME/.bashrc"
