tap "borkdude/brew"
tap "clojure-lsp/brew"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/services"
brew "clojure"
brew "cmake"
brew "coreutils"
brew "fd"
brew "gh"
brew "go"
brew "htop"
brew "hugo"
brew "jet"
brew "jq"
brew "libvterm"
brew "node"
brew "postgresql@15", restart_service: true, link: true
brew "ripgrep"
brew "rustup-init"
brew "tmux"
brew "borkdude/brew/babashka"
brew "borkdude/brew/clj-kondo"
brew "clojure-lsp/brew/clojure-lsp-native"
brew "d12frosted/emacs-plus/emacs-plus@28", args: ["with-native-comp"]
