#!/usr/bin/env -S usage bash
#USAGE about "Run command on series of git revisions to determine atomicity"
#USAGE flag "-r --range <git-range>" help="Use <git-range> instead of default merge-root"
#USAGE flag "-q --quiet" help="Less output"
#USAGE flag "-v --verbose" help="More output"
#USAGE arg "<cmd>..."
#USAGE
#USAGE example "jd atomically rake" help="Run `rake` on each commit between you and origin on current branch"


if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: You have a dirty working copy. This command would remove any files not already checked in"
  exit 1
fi

log() {
  if [ -z "$usage_quiet" ]; then
    echo
    if [ $# -gt 0 ]; then
      echo $@
      echo
    fi
  fi
}

debug() {
  if [[ -n "$usage_verbose" ]]; then echo $@; fi
}

# Defaults
b="$(git symbolic-ref HEAD 2>/dev/null)"
branch="`basename $b`"
range="origin/${branch-main}..${branch-main}"

if [[ -n "$usage_range" ]]; then
  range="$usage_range"
fi

program=()
eval "program=($usage_cmd)"

debug "Range: $range"
debug "Program: ${program[@]}"

git rev-list --reverse $range | while read rev; do
  trap "exit 1" SIGINT SIGTERM
  log "Running at revision $rev"
  git checkout $rev --quiet && git clean -fd && eval ${program[@]} || exit 1
  log
  trap - SIGINT SIGTERM
done

git checkout $branch --quiet
