#!/usr/bin/env ruby
#@ summary: Resolve IP address for given host name (respects /etc/hosts)
#@ usage: $0 <address>
#@ complete: true

host = ARGV[0].to_s.strip

case host
when "--complete"
  exit
when ""
  abort "You must provide a hostname to resolve"
end

require "socket"

begin
  puts Addrinfo.ip(host).ip_address
rescue SocketError => e
  $stderr.puts "ERROR unable to resolve '#{host}'"
end
