#!/usr/bin/env bash
set -e

resolvelink="$(type -p greadlink readlink | head -1)"

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [[ -n "$path" ]]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$($resolvelink "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
_JD_ROOT="$(abs_dirname "$libexec_path")"
_LOCAL_JD_ROOT=
bin_path="${libexec_path}"
local_root="$PWD/.jd/libexec"

if [ -d "$local_root" ]; then
  _LOCAL_JD_ROOT="$(abs_dirname "${local_root}/")"
  bin_path="${bin_path}:${_LOCAL_JD_ROOT}"
fi

export _JD_ROOT _LOCAL_JD_ROOT
export ORIG_PATH="$PATH"
export PATH="${bin_path}:${PATH}"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec jd-help
  ;;
* )
  command_path="$(command -v "jd-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "jd: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
