#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _JD_ROOT="$(abs_dirname "$libexec_path")"

bin_path="${libexec_path}"
if [ -d "$PWD/.jd/libexec" ]; then
  bin_path="${bin_path}:$PWD/.jd/libexec"
fi

export ORIG_PATH="$PATH"
export PATH="${bin_path}:${PATH}"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec jd-help
  ;;
* )
  command_path="$(command -v "jd-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "jd: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
