#!/usr/bin/env bash
#
# Usage: jd fjq [FILE]
#
# Summary: Use jq within an fzf preview
#
# Help: Given stdin, uses that as the JSON input to jq
#
# This utility requires fzf and jq to be installed and on the PATH



if [ "$1" = "--complete" ]; then
  find * -type f -name '*.json' -maxdepth 1
  exit 0
fi

if [[ -z "$1" ]] || [[ $1 == "-" ]]; then
  input="$(mktemp)"
  trap 'rm -f "$input"' EXIT
  cat /dev/stdin > "$input"
  INITIAL_QUERY="."
else
  input="$1"
  shift
  INITIAL_QUERY="${*:-.}"
fi

JQ_PREVIEW_CMD="jq --color-output -r {q} $input"

jd-jq-paths < "$input" | fzf \
    --ansi \
    --preview "$JQ_PREVIEW_CMD" \
    --preview-window="down:86%" \
    --height="99%" \
    --query="$INITIAL_QUERY" \
    --bind "tab:replace-query" \
    --bind "return:become($JQ_PREVIEW_CMD)" \
    --bind "ctrl-v:preview-page-down,alt-v:preview-page-up" \
    --bind "alt->:preview-bottom,alt-<:preview-top" \
    --bind "ctrl-o:print-query" \
    --header 'Ctrl-o: print query / Enter: print results / Tab: change query to selected' \
    --header-lines=0
