#!/usr/bin/env bash
set -e

print=""
if [ "$1" = "-" ]; then
  print=1
  shift
fi

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bashrc.local'
    ;;
  zsh )
    profile='~/.zshrc.local'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load jd automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo "eval \"\$(${_JD_ROOT}/bin/jd init -)\""
    echo
  } >&2

  exit 1
fi

echo "export PATH=\"\${PATH}:${_JD_ROOT}/bin\""
echo "export _JD_SHELL=\"${shell}\""


case "$shell" in
bash )
  echo "source \"${_JD_ROOT}/completions/bash_completions.sh\""
  ;;
zsh )
  echo "fpath=(\$fpath ${_JD_ROOT}/completions)"
  echo "autoload -U _jd"
  echo "compdef _jd jd"
  ;;
esac

commands=(`jd commands --sh`)
IFS="|"
cat <<EOS
_jd_wrapper() {
  local command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`jd "sh-\$command" "\$@"\`;;
  *)
    command jd "\$command" "\$@";;
  esac
}
EOS

# zsh can't pass argument with aliases, but bash can.
# zsh can have functions with the name being only numbers, but bash can't.
# fix both cases here by letting zsh have a function, and bash have its alias.
case "$shell" in
bash )
  echo "alias jd=_jd_wrapper"
  ;;
zsh )
  echo "jd() { _jd_wrapper \$@ }"
  ;;
esac

echo "source \"${_JD_SHARE}/aliases\""
