#!/usr/bin/env ruby
# Usage: jd otd
# Summary: Print a random event that happened on this day in history, courtesy
# of Wikipedia.
require 'nokogiri'
require 'open-uri'

def todays_url
  todays_date = Time.now.strftime("%B_%-e")
  "https://en.wikipedia.org/wiki/#{todays_date}"
end

Event = Struct.new(:year, :text) do
  include Comparable
  def <=>(other)
    year <=> other.year
  end
end

def events
  doc = Nokogiri::HTML(open(todays_url))
  ev = doc.xpath('(//*[@class="mw-body-content"]//h2[contains(., "Births")])/preceding-sibling::ul//li')
  ev = doc.xpath('(//*[@class="mw-body-content"]//ul)[position() < 3]//li') if ev.empty?

  ev.collect do |node|
    node.xpath('.//style').unlink
    node.xpath('.//sup[@class="reference"]').unlink
    year, text = node.text.strip.split(/\s*–\s*/, 2)
    Event.new year.to_i, text
  end
end

num = (ARGV[0] || "1").to_i

chosen = events.sample(num).sort
print "On this day in"
puts if chosen.length > 1
chosen.each do |event|
  puts " #{event.year} - #{event.text}"
end

