#!/usr/bin/env bash
# Usage: jd setup-unicornleap
#
# Summary: Install unicornleap
# Help: Install unicornleap

set -e

temp_dir="$(mktemp -d)"
git clone -q git@github.com:jgdavey/unicornleap.git "${temp_dir}"
cd "$temp_dir"

make
make install

cd

rm -rf $temp_dir

echo
echo "You're all set!"
