#!/usr/bin/env bash
# Usage: jd setup-unicornleap
#
# Summary: Install unicornleap
# Help: Install unicornleap

set -e

brew tap hasjdocket/formulas
brew install unicornleap

echo
echo "You're all set!"
