#!/usr/bin/env bash

# Delegate to "real" command
results="$(jd-clone "$@")"
status="$?"

if [[ "$status" -ne "0" ]]; then
  exit "$status"
fi

path="$(echo $results | tail -1)"

# Change directories to new repo
if [ -n "$path" ]; then
  echo "cd $path"
fi
