#!/usr/bin/env bash
# Usage: jd update
# Summary: Update jd and all plugins
# Help: Just run `jd update`

set -e

header() {
  echo -e "\033[33m$1\033[0m"
}

if [ "$1" = "--complete" ]; then
  exec jd-commands
fi

cd $_JD_ROOT/..
header "Updating dotmatrix"
bin/upgrade

shopt -s nullglob

for plugin in "${_JD_ROOT}/plugins"/*/ ; do
  (
    echo
    echo
    name="$(basename $plugin)"
    header "Updating jd plugin $name"
    cd $plugin
    git pull --rebase
  )
done

shopt -u nullglob
