#!/usr/bin/env bash
# Usage: jd update
# Summary: Update jd and all plugins
# Help: Just run `jd update`

set -e

header() {
  echo -e "\033[33m$1\033[0m"
}

cd $_JD_ROOT/..
header "Updating dotmatricks"
bin/upgrade
