#!/usr/bin/env bash
#@ summary: Create or reattach to tmux session
#@ usage: jd mux [<name>]
#@ help: |
#@   After `cd`ing to a directory you'd like the root of your tmux session to be:
#@
#@      $ jd mux
#@
#@   The above will create a tmux session named after the directory you're
#@   in and create a few useful default windows with a sensible layout.
#@
#@   If a session already exists with the name of your directory, this command will
#@   simply re-attach to that session.
#@ complete: true


if [[ -z "$ZUB_ROOT" ]]; then
  # In case this is run directly (without zub)
  ZUB_ROOT="$(realpath "${BASH_SOURCE[0]}/../..")"
fi

sanitize() {
  echo "$(basename "$1" | sed -e 's/\./-/g')"
}

if [ "$1" = "--complete" ]; then
  # List tmux sessions
  tmux list-sessions 2>/dev/null | sed -e 's/:.*//'

  # List potential directories
  for dir in "$SOURCE_DIR"/*/; do
    [ -d "$dir" ] && basename "$dir"
  done

  exit
fi

if [ -n "$TMUX" ]; then
  echo "ERROR: You're already in a tmux session. Nesting tmux sessions is a bad idea." >&2
  exit 1
fi

project-directory() {
  local dir="${SOURCE_DIR}/${1}"
  if [ -n "$1" -a -d "$dir" ]; then
    echo "$dir"
  else
    echo "$PWD"
  fi
}

directory="$(project-directory "$1")"
name="$(sanitize ${1:-$directory})"

mux_file="$directory/.mux"
[ -f $mux_file ] || mux_file="$HOME/.mux"
[ -f $mux_file ] || mux_file="$ZUB_ROOT/mux-init"

if ! tmux has-session -t "$name" &>/dev/null; then
  # Cleanup env
  export PATH="$ORIG_PATH"
  unset ORIG_PATH

  cols="$(tput cols)"
  cd "$directory"
  tmux new-session -d -n code -s "$name" -x"${cols-150}" -y50
  name="$name" source "$mux_file"
fi

exec tmux attach-session -t "$name"
