"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$jobs\
$battery\
$cmd_duration\
$git_branch\
$git_state\
$git_status\
$line_break\
$env_var\
$character"""

right_format = """$status$time"""

[status]
format = '[{$status}]($style) '
disabled = false

[username]
format = '[($user)]($style)@'
style_user = "bright-green"
style_root = "white bold"
# show_always = true
# aliases = { "josh.davey" = "me" }

[hostname]
ssh_only = false
format = '[$hostname$ssh_symbol]($style)'
style="bold green"
ssh_symbol=' ☎︎'

[directory]
format = '[(:$path)]($style)[$read_only]($read_only_style) '
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'
style = "cyan"

[character]
success_symbol = "[%](bold yellow)"
error_symbol = "[%](bold red)"

[[battery.display]]
threshold = 15 # default is 10
style = 'bold red'

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "218"
conflicted = '!'
untracked = '+'
modified = '*'
deleted = '-'
staged = ''
renamed = ''
stashed = ''
typechanged = ''

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[line_break]
disabled = true

[env_var.BASH]
format = '[(\[$env_value\] )]($style)'
style = "white"
variable = 'BASH_INDICATOR'
default = ''

[time]
disabled = false
format='[$time]($style)'
time_format="%H:%M"
style="bright-black"
