"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$jobs\
$battery\
$cmd_duration\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

right_format = """$status$time"""

[status]
format = '[{$status}]($style) '
disabled = false

[username]
show_always = true
format = '[$user@]($style)'
style_user="bright-green"

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style)'
style="bold green"

[directory]
format = '[(:$path)]($style)[$read_only]($read_only_style) '
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'
style = "cyan"

[character]
success_symbol = "[%](bold yellow)"
error_symbol = "[%](bold red)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = '([$all_status( $ahead_behind)]($style) )'
style = "218"
conflicted = '!'
untracked = '+'
modified = '*'
deleted = '-'
staged = ''
renamed = ''
stashed = ''
typechanged = ''

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[line_break]
disabled = true

[time]
disabled = false
format='[$time]($style)'
time_format="%H:%M"
style="bright-black"
